import { ReactNode } from "react";
import Header from "../header/Header";
import Navbar from "../navbar/Navbar";
import Footer from "../footer/Footer";
import Head from "next/head";
import ThemProvider from "@/context/ThemProvider";
import RotateScreen from "../rotateScreen/RotateScreen";

interface Props {
  children?: ReactNode;
  title: string;
}

const Layout = ({ children, title }: Props) => {
  return (
    <>
      <Head>
        <title>Mehrdad Azizkhani - {title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RotateScreen />
      <ThemProvider>
        <main className="bg-light-primary dark:bg-dark-primary relative">
          <Header />
          <Navbar />
          <section className="md:h-[calc(100vh-192px)] h-[calc(100dvh-112px)] px-4 flex items-center justify-center container mx-auto">
            <div className="relative w-[calc(100%-72px)] h-full z-10 overflow-y-scroll scrollbar-none snap-y snap-mandatory scroll-smooth">
              {children}
            </div>
          </section>
          <Footer />
          <div className="absolute top-0 w-full h-full flex justify-center items-center">
            <div className="mx-auto container flex justify-center items-center">
              <div className="md:h-[calc(100vh-96px)] h-[calc(100dvh-56px)] rounded-xl md:w-[calc(100%-72px)] w-[calc(100%-50px)] border-[1.5px] border-[#666666] dark:border-[#888888]"></div>
            </div>
          </div>
        </main>
      </ThemProvider>
    </>
  );
};

export default Layout;
